// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyxtisjnbrsaxqyvgojs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5eHRpc2puYnJzYXhxeXZnb2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDQ4OTcsImV4cCI6MjA2MDI4MDg5N30.GDYxIDFj77vuV4LRclNhUIr6gH3nm0MBiX5NfjvDnIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);